---
title: "Sample size calculations"
---

# Exercise 7.1
Assume you want to compare the concentration of a certain metabolite in blood samples of patients with a certain disease with samples from healthy control people. From a pilot sample, it is known that the standard deviation in the complete sample is 2 (SD = 2). A difference of $\delta = 3$ mml/l between the group means is considered as clinical relevant. If there is truly a difference of $\delta = 3$ mml/l between the group means, it is desired to detect this differences with a probability of 80 \%, i.e. you allow for a false negative probability of 100% - 80% = 20%.

How many samples per group are necessary to fulfill the above demand for the power of 80% ($\texttt{power.t.test}$)?


Assume in the above setting that a smaller difference, i.e. of $\delta = 0.1$ is considered as clinical relevant:

Change the value for the desired power and discuss with your neighbor the effect on the sample size. Turn also on the value of the standard deviation from the pilot sample.

Now, assume the researchers know that they can only effort to recruit $n=10$ patients per group. The researchers want to know what power they can achieve with this constraint for a 
specified $\delta$ of 1.3 and a standard deviation of 1.5.

# Exercise 7.2
Assume you want to compare the rate of infections between two different groups of subjects. The one group (A) was strongly exposed to some risk factor, the other group (B) was only weak exposed. From a study on a similar risk factor, it is known that the infection rate for group A is P1 = 25% and P2 = 18% for group B.

Determine the power to detect a difference between the effects rates of P1 - P2 = 7% given that
N=100 subjects can be recruited per group (\texttt{power.prop.test}):


Assume that a power of 80% is desired for the above study. Which sample sizes per group would be necessary?







